version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5000/udp:5000/udp"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  nginx:
    build: nginx/
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d/
    networks:
      - docker_elk
    ports:
      - "80:80"
    depends_on:
      - kibana

networks:
  docker_elk:
    driver: bridge
